-- Bathroom locations
table.insert(ProceduralDistributions["list"]["BathroomCabinet"].items, "RedDays.PantyLinerBox")
table.insert(ProceduralDistributions["list"]["BathroomCabinet"].items, 10)
table.insert(ProceduralDistributions["list"]["BathroomCabinet"].items, "RedDays.SanitaryPadBox")
table.insert(ProceduralDistributions["list"]["BathroomCabinet"].items, 10)
table.insert(ProceduralDistributions["list"]["BathroomCabinet"].items, "RedDays.TamponBox")
table.insert(ProceduralDistributions["list"]["BathroomCabinet"].items, 10)

table.insert(ProceduralDistributions["list"]["BathroomCounter"].items, "RedDays.PantyLinerBox")
table.insert(ProceduralDistributions["list"]["BathroomCounter"].items, 10)
table.insert(ProceduralDistributions["list"]["BathroomCounter"].items, "RedDays.SanitaryPadBox")
table.insert(ProceduralDistributions["list"]["BathroomCounter"].items, 10)
table.insert(ProceduralDistributions["list"]["BathroomCounter"].items, "RedDays.TamponBox")
table.insert(ProceduralDistributions["list"]["BathroomCounter"].items, 10)

table.insert(ProceduralDistributions["list"]["BathroomCounterNoMeds"].items, "RedDays.PantyLinerBox")
table.insert(ProceduralDistributions["list"]["BathroomCounterNoMeds"].items, 5)
table.insert(ProceduralDistributions["list"]["BathroomCounterNoMeds"].items, "RedDays.SanitaryPadBox")
table.insert(ProceduralDistributions["list"]["BathroomCounterNoMeds"].items, 5)
table.insert(ProceduralDistributions["list"]["BathroomCounterNoMeds"].items, "RedDays.TamponBox")
table.insert(ProceduralDistributions["list"]["BathroomCounterNoMeds"].items, 5)

table.insert(ProceduralDistributions["list"]["BathroomShelf"].items, "RedDays.PantyLinerBox")
table.insert(ProceduralDistributions["list"]["BathroomShelf"].items, 5)
table.insert(ProceduralDistributions["list"]["BathroomShelf"].items, "RedDays.SanitaryPadBox")
table.insert(ProceduralDistributions["list"]["BathroomShelf"].items, 5)
table.insert(ProceduralDistributions["list"]["BathroomShelf"].items, "RedDays.TamponBox")
table.insert(ProceduralDistributions["list"]["BathroomShelf"].items, 5)

-- Residential
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, "RedDays.PantyLinerBox")
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, 2.5)
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, "RedDays.SanitaryPadBox")
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, 2.5)
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, "RedDays.TamponBox")
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, 2.5)

-- Stores
--table.insert(ProceduralDistributions["list"]["Gigamart"].items, "RedDays.PantyLinerBox")
--table.insert(ProceduralDistributions["list"]["Gigamart"].items, 10)
--table.insert(ProceduralDistributions["list"]["Gigamart"].items, "RedDays.SanitaryPadBox")
--table.insert(ProceduralDistributions["list"]["Gigamart"].items, 10)
--table.insert(ProceduralDistributions["list"]["Gigamart"].items, "RedDays.TamponBox")
--table.insert(ProceduralDistributions["list"]["Gigamart"].items, 10)

table.insert(ProceduralDistributions["list"]["PharmacyCosmetics"].items, "RedDays.PantyLinerBox")
table.insert(ProceduralDistributions["list"]["PharmacyCosmetics"].items, 10)
table.insert(ProceduralDistributions["list"]["PharmacyCosmetics"].items, "RedDays.SanitaryPadBox")
table.insert(ProceduralDistributions["list"]["PharmacyCosmetics"].items, 10)
table.insert(ProceduralDistributions["list"]["PharmacyCosmetics"].items, "RedDays.TamponBox")
table.insert(ProceduralDistributions["list"]["PharmacyCosmetics"].items, 10)

table.insert(ProceduralDistributions["list"]["StoreShelfMedical"].items, "RedDays.PantyLinerBox")
table.insert(ProceduralDistributions["list"]["StoreShelfMedical"].items, 10)
table.insert(ProceduralDistributions["list"]["StoreShelfMedical"].items, "RedDays.SanitaryPadBox")
table.insert(ProceduralDistributions["list"]["StoreShelfMedical"].items, 10)
table.insert(ProceduralDistributions["list"]["StoreShelfMedical"].items, "RedDays.TamponBox")
table.insert(ProceduralDistributions["list"]["StoreShelfMedical"].items, 10)

--table.insert(ProceduralDistributions["list"]["StoreShelf"].items, "RedDays.PantyLinerBox")
--table.insert(ProceduralDistributions["list"]["StoreShelf"].items, 10)
--table.insert(ProceduralDistributions["list"]["StoreShelf"].items, "RedDays.SanitaryPadBox")
--table.insert(ProceduralDistributions["list"]["StoreShelf"].items, 10)
--table.insert(ProceduralDistributions["list"]["StoreShelf"].items, "RedDays.TamponBox")
--table.insert(ProceduralDistributions["list"]["StoreShelf"].items, 10)

-- Medical
table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, "RedDays.PantyLinerBox")
table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, 10)
table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, "RedDays.SanitaryPadBox")
table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, 10)
table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, "RedDays.TamponBox")
table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, 10)

table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, "RedDays.PantyLinerBox")
table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, 5)
table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, "RedDays.SanitaryPadBox")
table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, 5)
table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, "RedDays.TamponBox")
table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, 5)